import { Product } from './types';

export const defaultProducts: Product[] = [
  {
    id: 'p001',
    name: 'Katan Silk Banarasi Saree with Zari Border',
    slug: 'katan-silk-banarasi-saree-zari-border',
    category: 'saree',
    fabric: 'Katan Silk',
    occasion: ['bridal', 'wedding', 'reception'],
    priceINR: 18500,
    priceEUR: 210,
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&auto=format&fit=crop&q=80'],
    description: 'Handpicked Banarasi saree with a timeless zari border, chosen for festive and bridal wardrobes.',
    shortDesc: 'Pure Katan silk Banarasi saree with zari border.',
    stock: 2,
    featured: true,
    newArrival: false,
    colors: ['Deep Crimson', 'Midnight Navy', 'Bottle Green'],
    tags: ['banarasi saree', 'katan silk saree', 'bridal saree'],
    weight: '600g',
    careInstructions: 'Dry clean only. Store in muslin cloth away from direct sunlight.',
    createdAt: '2025-08-15',
    updatedAt: '2025-08-15'
  },
  {
    id: 'p002',
    name: 'Organza Embroidered Bridal Lehenga with Dupatta',
    slug: 'organza-embroidered-bridal-lehenga-dupatta',
    category: 'lehenga',
    fabric: 'Organza',
    occasion: ['bridal', 'wedding', 'reception', 'sangeet'],
    priceINR: 32000,
    priceEUR: 365,
    images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=1200&auto=format&fit=crop&q=80'],
    description: 'Statement bridal lehenga with heavy embroidery, matching dupatta, and occasion-ready finish.',
    shortDesc: 'Heavy embroidered bridal lehenga with matching dupatta.',
    stock: 1,
    featured: true,
    newArrival: true,
    colors: ['Blush Rose', 'Ivory Gold', 'Scarlet Red'],
    tags: ['bridal lehenga', 'organza lehenga', 'embroidered lehenga'],
    weight: '1.2kg',
    careInstructions: 'Dry clean only. Store flat in the bag provided.',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01'
  },
  {
    id: 'p003',
    name: 'Chanderi Cotton Silk Saree with Gold Border',
    slug: 'chanderi-cotton-silk-saree-gold-border',
    category: 'saree',
    fabric: 'Chanderi',
    occasion: ['festival', 'casual', 'puja'],
    priceINR: 6800,
    priceEUR: 78,
    images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=1200&auto=format&fit=crop&q=80'],
    description: 'Lightweight Chanderi saree with classic gold border for elegant festive dressing.',
    shortDesc: 'Easy drape Chanderi saree with refined gold border.',
    stock: 4,
    featured: true,
    newArrival: false,
    colors: ['Champagne', 'Soft Peach', 'Moss Green'],
    tags: ['chanderi saree', 'festival saree', 'lightweight saree'],
    weight: '450g',
    careInstructions: 'Dry clean preferred. Steam gently on low heat.',
    createdAt: '2025-08-20',
    updatedAt: '2025-08-20'
  },
  {
    id: 'p004',
    name: 'Patola Inspired Silk Saree',
    slug: 'patola-inspired-silk-saree',
    category: 'saree',
    fabric: 'Silk Blend',
    occasion: ['wedding', 'festival', 'party'],
    priceINR: 9200,
    priceEUR: 105,
    images: ['https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=1200&auto=format&fit=crop&q=80'],
    description: 'A vibrant silk blend saree inspired by traditional Patola aesthetics and festive color play.',
    shortDesc: 'Rich silk blend saree with festive statement look.',
    stock: 3,
    featured: false,
    newArrival: true,
    colors: ['Royal Blue', 'Rust Orange', 'Rani Pink'],
    tags: ['patola saree', 'silk saree', 'wedding saree'],
    weight: '520g',
    careInstructions: 'Dry clean only.',
    createdAt: '2025-09-10',
    updatedAt: '2025-09-10'
  },
  {
    id: 'p005',
    name: 'Velvet Bridal Lehenga Set',
    slug: 'velvet-bridal-lehenga-set',
    category: 'lehenga',
    fabric: 'Velvet',
    occasion: ['bridal', 'wedding', 'reception'],
    priceINR: 38500,
    priceEUR: 440,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1200&auto=format&fit=crop&q=80'],
    description: 'Velvet lehenga chosen for winter weddings and rich bridal styling.',
    shortDesc: 'Velvet bridal lehenga with premium occasion finish.',
    stock: 1,
    featured: false,
    newArrival: false,
    colors: ['Wine', 'Emerald', 'Maroon'],
    tags: ['velvet lehenga', 'bridal wear', 'winter wedding'],
    weight: '1.5kg',
    careInstructions: 'Dry clean only. Avoid folding embroidery lines sharply.',
    createdAt: '2025-08-28',
    updatedAt: '2025-08-28'
  },
  {
    id: 'p006',
    name: 'Tissue Silk Saree with Contrast Border',
    slug: 'tissue-silk-saree-contrast-border',
    category: 'saree',
    fabric: 'Tissue Silk',
    occasion: ['party', 'festival', 'reception'],
    priceINR: 11200,
    priceEUR: 128,
    images: ['https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1200&auto=format&fit=crop&q=80'],
    description: 'A luminous tissue silk saree that works beautifully for receptions and elegant evening dressing.',
    shortDesc: 'Premium tissue silk saree with striking contrast border.',
    stock: 5,
    featured: true,
    newArrival: true,
    colors: ['Gold Beige', 'Rose Gold', 'Chiku'],
    tags: ['tissue silk saree', 'party saree', 'premium saree'],
    weight: '500g',
    careInstructions: 'Dry clean only. Handle delicately around the border.',
    createdAt: '2025-09-12',
    updatedAt: '2025-09-12'
  }
];

export const formatINR = (value: number) =>
  new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);

export const featuredProducts = defaultProducts.filter((product) => product.featured);
